### ISSUE TITLE
Azureplugin is empty

### ISSUE THREAD

**Issue by jhewetson** [microsoft/PowerApps-Samples#25] opened 2019-07-03 04:31 UTC
Howzit, I noticed this plugin is empty.
[https://github.com/microsoft/PowerApps-Samples/blob/master/cds/orgsvc/C%23/Azureplugin/Azureplugin/Program.cs](url)

I'm guessing its the same as this one, I could do a PR but wanted to check with you since there is a lot of other work in this repo regarding class names, refactoring and the whole CDS movement.
[https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/write-custom-azure-aware-plugin](url)

Thought I'd provide some feedback.

Thanks for the cool documentation by the way.👏

**Comment by Nkrb** [comment] 2019-07-09 18:10
@jhewetson Thanks for the feedback. The issue is resolved and the updates are pushed to live. Closing this issue.

**Closed by Nkrb** 2019-07-09 18:10 UTC
