### ISSUE TITLE
Canvasgrid showing no data when come back from another screen? 

### ISSUE THREAD

**Issue by tejasPriya** [microsoft/PowerApps-Samples#238] opened 2022-02-09 09:25 UTC
Hi,
I am using CanvasGrid PCF control in Canvas App.
When clicking on row of canvas grid and navigating to other screen and come back to the same screen where canvas grid is present, there I got blank data in canvas grid. Why does this happen to me?

Steps to reproduce issue:
1)Added canvas grid to screen 1 and set data source  to Customer entity, item property to Customer entity and OnSelect property set to "Navigate(Screen2)".
1)Added a form on screen 2 and set its item property to CanvasGrid.selected. Also added back icon and set it to "Navigate(Screen1)"

When coming back to Screen1 from Screen2, it shows a blank grid.

**Comment by JimDaly** [comment] 2022-03-03 01:20
@tejasPriya 
Are you experiencing an issue with one of the samples we have published?

**Comment by JimDaly** [comment] 2022-03-24 04:54
@tejasPriya

Looks like @scottdurow noticed this issue and has made a change to the canvas grid control sample.
https://github.com/microsoft/PowerApps-Samples/tree/master/component-framework/CanvasGridControl 
Does this address the issue?

**Comment by JimDaly** [comment] 2022-06-12 18:28
“Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue."

**Closed by JimDaly** 2022-06-12 18:28 UTC
